Invoked as: ./configure 
Tclsh: /usr/bin/tclsh
Failed: cc -g -Os conftest__.c -o conftest__
conftest__.c:1:13: warning: conflicting types for built-in function ‘sin’; expected ‘double(double)’ [-Wbuiltin-declaration-mismatch]
    1 | extern void sin(void);
      |             ^~~
conftest__.c:1:1: note: ‘sin’ is declared in header ‘<math.h>’
  +++ |+#include <math.h>
    1 | extern void sin(void);
/usr/bin/ld: /tmp/ccXG52da.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `sin'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void sin(void);
int main(void) {
sin();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lm
/usr/bin/ld: /tmp/cc6llkIW.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void dlopen(void);
int main(void) {
dlopen();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -ldl -lm
/usr/bin/ld: /tmp/cc0hzmgV.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void inflateEnd(void);
int main(void) {
inflateEnd();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -ldl -lm
/usr/bin/ld: /tmp/ccXFwhcG.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `compressBound'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void compressBound(void);
int main(void) {
compressBound();
return 0;
}
============
Failed: cc -c -g -Os conftest__.c -o conftest__.o
conftest__.c:2:10: fatal error: bind/resolv.h: No such file or directory
    2 | #include <bind/resolv.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
child process exited abnormally
============
The failed code was:
#include <netinet/in.h>
#include <bind/resolv.h>
int main(void) {

return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -ldl -lm
/usr/bin/ld: /tmp/ccMi9sJn.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `dn_expand'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void dn_expand(void);
int main(void) {
dn_expand();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/ccfMignK.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `dn_expand'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void dn_expand(void);
int main(void) {
dn_expand();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -ldl -lm
/usr/bin/ld: /tmp/ccmQ59k6.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `ns_name_uncompress'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void ns_name_uncompress(void);
int main(void) {
ns_name_uncompress();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lbind -ldl -lm
/usr/bin/ld: cannot find -lbind
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void ns_name_uncompress(void);
int main(void) {
ns_name_uncompress();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/cc95oRVE.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `res_query'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void res_query(void);
int main(void) {
res_query();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lbind -lresolv -ldl -lm
/usr/bin/ld: cannot find -lbind
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void res_query(void);
int main(void) {
res_query();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -lresolv -ldl -lm
/usr/bin/ld: /tmp/ccIWteHo.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `res_query'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void res_query(void);
int main(void) {
res_query();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/ccecOO4a.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `res_9_ns_initparse'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void res_9_ns_initparse(void);
int main(void) {
res_9_ns_initparse();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -lresolv -ldl -lm
/usr/bin/ld: /tmp/ccp1N4Jv.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `res_9_ns_initparse'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void res_9_ns_initparse(void);
int main(void) {
res_9_ns_initparse();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/cciFrqr1.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `pledge'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void pledge(void);
int main(void) {
pledge();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/cc4dnSsc.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `getpassphrase'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void getpassphrase(void);
int main(void) {
getpassphrase();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lresolv -ldl -lm
/usr/bin/ld: /tmp/ccG923XU.o: in function `main':
/home/ecs-user/depot/Fossil-1205ec86/conftest__.c:3: undefined reference to `fuse_mount'
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void fuse_mount(void);
int main(void) {
fuse_mount();
return 0;
}
============
Failed: cc -g -Os conftest__.c -o conftest__ -lfuse -lresolv -ldl -lm
/usr/bin/ld: cannot find -lfuse
collect2: error: ld returned 1 exit status
child process exited abnormally
============
The failed code was:
extern void fuse_mount(void);
int main(void) {
fuse_mount();
return 0;
}
============
